#require 'guard/compat/plugin'
# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"


module ::Guard
  class Mix < Plugin

    def mix
      template = File.read('slides.template.html')
      slides = File.read('slides.md')
      result = template.sub(/<--slides-->/, slides)
      File.write('slides.html', result)
      slides = File.read('runconf.md')
      result = template.sub(/<--slides-->/, slides)
      File.write('runconf.html', result)
    end

    def run_all
      mix()
    end
    def run_on_modifications(paths)
      mix()
    end
  end
end

guard 'mix' do
  watch('slides.md')
  watch('runconf.md')
  watch('slides.template.html')
end
